enableGlobalCache: false

npmPublishAccess: "public"
npmScopes:
  axiscommunications:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@types/hoist-non-react-statics@*":
    dependencies:
      react: "*"
  "@types/react-dom@*":
    dependencies:
      react: "*"
  "@types/styled-components@*":
    dependencies:
      react: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.js
