# Generates a new version commit (through yarn) and
# pushes the tagged commit, which will then trigger
# the publish workflow.
name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Generate new version
      run: |
        yarn release
        git config --global user.name 'release-action'
        git config --global user.email 'steabert@users.noreply.github.com'
        git push --follow-tags
