# Generates a new version commit (through yarn) and
# pushes the tagged commit, which will then trigger
# the publish workflow.
name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Generate new version
      run: |
        yarn release
        git push --follow-tags
